stages:
  - build-fpga
  - build-esp
  - deploy

fpga-firmware:
  stage: build-fpga
  script: 
    - ./Core/source/ram/create_text_ram.pl
    - script -qfc "$(printf "%q " "/root/build")" /dev/null
  artifacts:
    paths:
    - Core/output_files/*.jic
    - Core/output_files/*.rbf
    - Core/output_files/*.dc
  tags:
    - dreamcast-hdmi
  only:
    - develop
    - master
    - experimental

esp-firmware:
  stage: build-esp
  script:
    - "cd FirmwareManager"
    - "./local/prepare-index-html"
    - "cat data.in/changelog.in | tr -d '\n\t' > data/changelog"
    - "export SOURCE_DATE_EPOCH=$(git --no-pager log -1 --pretty='format:%ct' src)"
    - "echo $SOURCE_DATE_EPOCH"
    - "pio run -t clean"
    - "pio run"
    # firmware.dc
    - "cp ../Core/output_files/DCxPlus-default.dc data/firmware.dc"
    - "md5sum data/firmware.dc | awk '{print $1;}' > data/etc/last_flash_md5"
    - "md5sum data/firmware.dc | awk '{print $1;}' > data/firmware.dc.md5"
    # firmware.bin
    - "md5sum .pioenvs/esp07s/firmware.bin | awk '{print $1;}' > data/etc/last_esp_flash_md5"
    - "md5sum .pioenvs/esp07s/firmware.bin | awk '{print $1;}' > data/firmware.bin.md5"
    # index.html
    - "md5sum data/index.html.gz | awk '{print $1;}' > data/index.html.gz.md5"
    - "md5sum data/index.html.gz | awk '{print $1;}' > data/esp.index.html.gz.md5"
    # finally build spiffs
    - "pio run -t buildfs"
  artifacts:
    paths:
    - FirmwareManager/.pioenvs/esp07s/firmware.bin
    - FirmwareManager/.pioenvs/esp07s/spiffs.bin
    - FirmwareManager/data/index.html.gz
    - FirmwareManager/data/changelog
  dependencies:
    - fpga-firmware
  tags:
    - platformio
  only:
    - develop
    - master
    - experimental

fpga-publish:
  stage: deploy
  script: create-index-html
  artifacts:
    expire_in: 1 sec
  dependencies:
    - fpga-firmware
  tags:
    - index-gen
  only:
    - develop
    - master
    - experimental

esp-publish:
  stage: deploy
  script: create-index-html-esp
  artifacts:
    expire_in: 1 sec
  dependencies:
    - esp-firmware
  tags:
    - index-gen
  only:
    - develop
    - master
    - experimental
