stages:
  - build-fpga
  - build-esp
  - deploy
  - publish

fpga-firmware:
  stage: build-fpga
  script: 
    - ./Core/source/ram/create_text_ram.pl
    - script -qfc "$(printf "%q " "/root/build")" /dev/null
  artifacts:
    name: "fpga-firmware-${CI_COMMIT_REF_NAME}"
    paths:
    - Core/output_files/*.jic
    - Core/output_files/*.rbf
    - Core/output_files/*.dc
  tags:
    - dreamcast-hdmi
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

esp-firmware:
  image:
    name: chriz2600/platformio:4.0.0
  stage: build-esp
  script:
    - "./build-all"
  artifacts:
    name: "esp-firmware-${CI_COMMIT_REF_NAME}"
    paths:
    - FirmwareManager/.pio/build/hq2x/firmware.bin
    - FirmwareManager/.pio/build/hq2x/spiffs.bin
    - FirmwareManager/data/hq2x-changelog
    - FirmwareManager/.pio/build/std/firmware.bin
    - FirmwareManager/.pio/build/std/spiffs.bin
    - FirmwareManager/data/std-changelog
    - FirmwareManager/data/index.html.gz
  dependencies:
    - fpga-firmware
  tags:
    - platformio
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

fpga-publish:
  stage: deploy
  script: create-index-html
  artifacts:
    expire_in: 1 sec
  dependencies:
    - fpga-firmware
  tags:
    - index-gen
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

esp-publish:
  stage: deploy
  script: 
    - "create-index-html-esp std"
    - "create-index-html-esp hq2x"
  artifacts:
    expire_in: 1 sec
  dependencies:
    - esp-firmware
  tags:
    - index-gen
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

finish-publish:
  stage: publish
  script: dc-atomic-move
  artifacts:
    expire_in: 1 sec
  dependencies:
    - fpga-publish
    - esp-publish
  tags:
    - index-gen
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags
