stages:
  - build-firmware-utils
  - build-fpga
  - build-esp
  - deploy
  - publish

firmware-utils:
  image:
    name: chriz2600/firmware-utils-builder:latest
  stage: build-firmware-utils
  script:
    - "cd firmware-utils"
    - "make install"
  artifacts:
    name: "firmware-utils-${CI_COMMIT_REF_NAME}"
    paths:
      - firmware-utils/firmware-packer
      - firmware-utils/firmware-unpacker
  tags:
    - dreamcast-hdmi
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

fpga-firmware:
  image:
      name: chriz2600/quartus-lite:latest
  stage: build-fpga
  script: 
    - ./Core/source/ram/create_text_ram.pl
    - script -qfc "$(printf "%q " "./Core/build-all")" /dev/null
  artifacts:
    name: "fpga-firmware-${CI_COMMIT_REF_NAME}"
    paths:
      - Core/output_files/std/*.jic
      - Core/output_files/std/*.rbf
      - Core/output_files/std/*.dc
      - Core/output_files/hq2x/*.jic
      - Core/output_files/hq2x/*.rbf
      - Core/output_files/hq2x/*.dc
  dependencies:
    - firmware-utils
  tags:
    - dreamcast-hdmi
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

esp-firmware:
  image:
    name: chriz2600/platformio:4.0.0
  stage: build-esp
  script:
    - "./FirmwareManager/build-all"
  artifacts:
    name: "esp-firmware-${CI_COMMIT_REF_NAME}"
    paths:
      - FirmwareManager/.pio/build/std/firmware.bin
      - FirmwareManager/.pio/build/std/spiffs.bin
      - FirmwareManager/.pio/build/std/changelog
      - FirmwareManager/.pio/build/hq2x/firmware.bin
      - FirmwareManager/.pio/build/hq2x/spiffs.bin
      - FirmwareManager/.pio/build/hq2x/changelog
      - FirmwareManager/data/index.html.gz
  dependencies:
    - fpga-firmware
  tags:
    - platformio
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

fpga-publish:
  stage: deploy
  script: 
    - "create-index-html std"
    - "create-index-html hq2x"
  artifacts:
    expire_in: 1 sec
  dependencies:
    - fpga-firmware
  tags:
    - index-gen
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

esp-publish:
  stage: deploy
  script: 
    - "create-index-html-esp std"
    - "create-index-html-esp hq2x"
  artifacts:
    expire_in: 1 sec
  dependencies:
    - esp-firmware
  tags:
    - index-gen
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

finish-publish:
  stage: publish
  script:
    - "dc-atomic-move std"
    - "dc-atomic-move hq2x"
  artifacts:
    expire_in: 1 sec
  dependencies:
    - fpga-publish
    - esp-publish
  tags:
    - index-gen
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags
