stages:
  - build-fpga
  - build-esp
  - deploy

fpga-firmware:
  stage: build-fpga
  script: 
    - ./Core/create_test_text_ram.pl
    - script -qfc "$(printf "%q " "/root/build")" /dev/null
  artifacts:
    paths:
    - Core/output_files/*.jic
    - Core/output_files/*.rbf
    - Core/output_files/*.dc
  tags:
    - dreamcast-hdmi

esp-firmware:
  stage: build-esp
  script:
    - "cd FirmwareManager"
    - "./local/prepare-index-html"
    - "./local/prepare-fw-version"
    - "pio run"
    - "cp ../Core/output_files/DCxPlus-default.dc data/firmware.dc"
    - "md5sum data/firmware.dc | awk '{print $1;}' > data/firmware.dc.md5"
    - "pio run -t buildfs"
  artifacts:
    paths:
    - FirmwareManager/.pioenvs/esp07s/firmware.bin
    - FirmwareManager/.pioenvs/esp07s/spiffs.bin
    - FirmwareManager/data/index.html.gz
  dependencies:
    - fpga-firmware
  tags:
    - platformio

fpga-publish:
  stage: deploy
  script: create-index-html
  artifacts:
    expire_in: 1 sec
  dependencies:
    - fpga-firmware
  tags:
    - index-gen

esp-publish:
  stage: deploy
  script: create-index-html-esp
  artifacts:
    expire_in: 1 sec
  dependencies:
    - esp-firmware
  tags:
    - index-gen
