
fpga-firmware:
  stage: build
  script: 
    - ./Core/create_test_text_ram.pl
    - script -qfc "$(printf "%q " "/root/build")" /dev/null
  artifacts:
    paths:
    - Core/output_files/*.jic
    - Core/output_files/*.rbf
    - Core/output_files/*.dc
  tags:
    - dreamcast-hdmi

esp-firmware:
  stage: build
  script:
    - "cd FirmwareManager"
    - "./local/prepare-index-html"
    - "./local/prepare-fw-version"
    - "pio run"
    - "pio run -t buildfs"
    - "mkdir -p /srv/esp/${CI_COMMIT_REF_NAME}"
    - "chmod 777 /srv/esp/${CI_COMMIT_REF_NAME}"
    - "cp FirmwareManager/.pioenvs/esp07s/firmware.bin /srv/esp/${CI_COMMIT_REF_NAME}/4MB-firmware.bin"
    - "cp FirmwareManager/.pioenvs/esp07s/spiffs.bin /srv/esp/${CI_COMMIT_REF_NAME}/4MB-spiffs.bin"
    - "cp FirmwareManager/data/index.html.gz /srv/esp/${CI_COMMIT_REF_NAME}/esp.index.html.gz"
    - "ls -alF /srv/esp/${CI_COMMIT_REF_NAME}/"
  artifacts:
    paths:
    - FirmwareManager/.pioenvs/esp07s/firmware.bin
    - FirmwareManager/.pioenvs/esp07s/spiffs.bin
    - FirmwareManager/data/index.html.gz
  tags:
    - platformio

fpga-publish:
  stage: deploy
  script: create-index-html
  artifacts:
    expire_in: 1 sec
  dependencies:
    - fpga-firmware
  tags:
    - index-gen

esp-publish:
  stage: deploy
  script: create-index-html-esp
  artifacts:
    expire_in: 1 sec
  dependencies:
    - esp-firmware
  tags:
    - index-gen
